spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: AmazonAndDocker
  sql-datasource:
    jdbc-url: jdbc:mysql://localhost:3306/amazon
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#Mongo db configurations
  mongodb-remote:
    host: localhost
    port: 27017
    collection: mongocollection
    driver:
      class: mongodb.jdbc.MongoDriver
    respositories:
      enabled: true
#Jpa update configurations
  jpa:
    hibernate:
      ddl-auto: update
#JPA
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

        
server:
   port: 8080
   
amazon:
  s3:
    accessToken:
    secret:
    bucket:
  dynamodb:
    accessKey:
    secretKey:
    region: us-east-2
    
